### ISSUE TITLE
Add FAQ about styling

### ISSUE THREAD

**Issue by ewels** [ewels/cpt-bootstrap-carousel#78]
Lots of people keep asking about how to change the appearance of the caption. Would be good to add a mention about custom css. _eg:_:

```css
carousel-caption h4 {
    color: <colour>;
    background-color: <colour>;
}
```
